// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVythXz6RGZ7mWGAizCvu5gt57akiTyu0',
    appId: '1:303514847232:web:1df89cb5330ec8608330e5',
    messagingSenderId: '303514847232',
    projectId: 'taskpro-a4d5c',
    authDomain: 'taskpro-a4d5c.firebaseapp.com',
    storageBucket: 'taskpro-a4d5c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlZWznVrt30eFPdDBkWB96p5VSpiqPoOo',
    appId: '1:303514847232:android:b3c7eb86ef99c4198330e5',
    messagingSenderId: '303514847232',
    projectId: 'taskpro-a4d5c',
    storageBucket: 'taskpro-a4d5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADEiyTpE7afQvUPSI7W7RwysbElqAcOos',
    appId: '1:303514847232:ios:ba9b44e2e755aff38330e5',
    messagingSenderId: '303514847232',
    projectId: 'taskpro-a4d5c',
    storageBucket: 'taskpro-a4d5c.appspot.com',
    iosBundleId: 'com.example.taskproUser',
  );
}
